### ISSUE TITLE
[Enigma] Структура

### ISSUE THREAD

**Issue by pavel-b-novikov** [mkvd/nsudotnet#1]
Объясните необходимость использования структуры для хранения информации о расшифровке

**Comment by pavel-b-novikov** [comment]
То есть я правильно понимаю, что для расшифровки у вас создается ажно целый Request, а вот для передачи ключей вы используете Tuple?

**Comment by mkvd** [comment]
"Необходимости" нет. Вы считаете использование структур нужно минимизировать?

**Comment by pavel-b-novikov** [comment]
Нет, я считаю что если вы используете что-либо, то четко должны понимать зачем.

**Comment by mkvd** [comment]
Можете пояснить суть претензии пожалуйста. Вам не нравится то, что я использовал именно структуру, вместо класса или не нравится, что я вообще создал для этого новый тип?

**Comment by pavel-b-novikov** [comment]
Мне не нравится что вы использовали фичу языка и толком не можете объяснить что она делает и зачем она вам в этом конкретном случае.

**Comment by mkvd** [comment]
В данном случае она ничего особенно не даёт, просто способ хранения.
Если вы про то, что struct можно разметить на стеке - я это знаю :)

**Comment by pavel-b-novikov** [comment]
И что у вас в данном конкретном случае окажется на стеке?

**Comment by mkvd** [comment]
Значение enum'а и 4 референса строк

**Comment by mkvd** [comment]
Кажется я понял почему это плохо

**Comment by pavel-b-novikov** [comment]
Нет, все верно. Вы по сути сделал структуру чтобы тягать по стеку 1 int и 4 референса на строки - читай тоже int-ы. Поэтому я и спрашиваю - вам оно сильно надо?

**Comment by mkvd** [comment]
Норм если я просто в класс переделаю с { get; set; } ? Тогда не будет тягаться.

**Comment by pavel-b-novikov** [comment]
В смысле? Get/set - это просто методы

**Comment by mkvd** [comment]
Я имел ввиду с точки зрения дизайна.

**Comment by pavel-b-novikov** [comment]
А. Ну само собой.
