### ISSUE TITLE
[Enigma] .GetAwaiter().GetResult()

### ISSUE THREAD

**Issue by pavel-b-novikov** [mkvd/nsudotnet#2]
Вообще-то это методы для компилятора, а не для вас. Сделайте нормальное ожидание завершения асинхронной таски

**Comment by mkvd** [comment]
Я ведь использовал это только в одном месте, чтобы сделать MainAsync. Я так понимаю что если там написать await то он не дождётся.

**Comment by pavel-b-novikov** [comment]
Само собой не дождется. Однако для ожидания задач есть более правильный способ, который я показывал на лекции

**Comment by mkvd** [comment]
Пойдёт как в c57dd9e98774dc740fc87b57d74419232df90d20 ?

`MainAsync(args).Wait();`

**Comment by mkvd** [comment]
Не буду врать, я видимо прозевал что вы говорили на лекции по этому поводу. Но если не использовать методы для компилятора, то есть `Task.WaitAll` и `Task.WaitAny`, которые уж точно сделаны для пользователя. Так что правильный вариант наверное: `Task.WhenAny(MainAsync(args));`.

**Comment by pavel-b-novikov** [comment]
Пойдет
