### ISSUE TITLE
General

### ISSUE THREAD

**Issue by mkvd** [mkvd/nsudotnet#5]
@pavel-b-novikov 

Поменял имена папок солюшенов и проектов. Надеюсь теперь ваша система их найдёт. И что это переименование не помешает уже начатой проверке Enigma.

**Comment by pavel-b-novikov** [comment]
Не нашла. У всех нашла, а вот вашу не нашла. Удивительно, правда?

**Comment by mkvd** [comment]
Да. Особенно то, что другую задачу нашла, несмотря на то, что я что-то сделал неправильно.

**Comment by mkvd** [comment]
Может это связано с тем, что репозиторий стал публичным уже после того как я закоммитил этот солюшн?

**Comment by pavel-b-novikov** [comment]
> Katchik.Nsudotnet.RssForwarder

Это связано с тем, что вы плохо прочитали мануал и неправильно написали техническое название

**Comment by mkvd** [comment]
> Чтобы начать новую задачу - заходите в nsudotnet, создаете там новую подпапку. Называете ее следующим образом: ФамилиТранслитом.Nsudotnet.ИмяЗадачи.

Вы конечно извините, но из этого совершенно не ясно, что имя задачи имеет принципиальное значение :)

Сейчас переименую.

**Comment by pavel-b-novikov** [comment]
Опять же - вот всему курсу ясно, а вам нет. Ну как так?

**Comment by mkvd** [comment]
Теперь должно найтись.
