### ISSUE TITLE
[Rss2Email] Cancellation token

### ISSUE THREAD

**Issue by pavel-b-novikov** [mkvd/nsudotnet#7]
В вашей программе никак не используется?

**Comment by mkvd** [comment]
Протягивается но не используется

**Comment by pavel-b-novikov** [comment]
сделайте так, чтобы использовался. Например прерывал все операции по Ctrl-C

**Comment by pavel-b-novikov** [comment]
Пойдет. 

Почитайте про диспоз тасок: https://blogs.msdn.microsoft.com/pfxteam/2012/03/25/do-i-need-to-dispose-of-tasks/
