### ISSUE TITLE
[Rss2Email] The Living End

### ISSUE THREAD

**Issue by pavel-b-novikov** [mkvd/nsudotnet#8]
Сделайте вместо просмотра AppSetting-ов нормальную секцию конфигурации.

Материал по теме: https://msdn.microsoft.com/en-us/library/2tw134k3.aspx

**Comment by mkvd** [comment]
Вы получаете уведомления о коммитах по теме?

**Comment by pavel-b-novikov** [comment]
Нет. Вас 26 человек. Каждый делает по 5-15 коммитов. У меня есть доступ только к web API гитхаба, а не к репозиториям. Как вы предлагаете парсить эту информацию?

**Comment by mkvd** [comment]
В общем я поправил оба момента вчера, гляньте плз.

**Comment by pavel-b-novikov** [comment]
Хорошо. Только в один файл это скидывать не стоило
